version: "3.8"
services:
  openresty:
    image: lightpath/openresty:latest
    build: .
    container_name: lightpath-openresty
    ports:
      - "80:80"
      - "443:443"
      - "2841:2841"
    environment:
      - SERVER_ID:'NY-1'
      - SERVER_COLO:'US'
      - SERVER_NAME:'edge-ny-1.lightpath-cdn.net'
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/src:/usr/local/openresty/lualib/lightpath
    depends_on:
      - redis
      - clickhouse
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lightpath
      - POSTGRES_USER=lightpath
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    container_name: lightpath-redis
    ports:
      - "6379:6379"
  clickhouse:
    image: yandex/clickhouse-server
    container_name: lightpath-clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./analytics/clickhouse_schema.sql:/docker-entrypoint-initdb.d/schema.sql
  vector:
    image: timberio/vector:nightly-2021-08-26-alpine
    container_name: lightpath-vector
    ports:
      - "1337:1337"
    volumes:
      - ./analytics/vector.toml:/etc/vector/vector.toml
    depends_on:
      - clickhouse
